In [3]:
import pandas as pd

In [5]:
df = pd.read_csv(r'F:\Airline_Delay.csv')
df

,year,month,carrier,carrier_name,airport,arr_flights,arr_del15,arr_cancelled,arr_delay,carrier_delay,late_aircraft_delay
0,2023,8,9E,Endeavor Air Inc.,ABE,89.0,13.0,2.0,1375.0,71.0,425.0
1,2023,8,9E,Endeavor Air Inc.,ABY,62.0,10.0,0.0,799.0,218.0,518.0
2,2023,8,9E,Endeavor Air Inc.,AEX,62.0,10.0,1.0,766.0,56.0,444.0
3,2023,8,9E,Endeavor Air Inc.,AGS,66.0,12.0,1.0,1397.0,471.0,218.0
4,2023,8,9E,Endeavor Air Inc.,ALB,92.0,22.0,2.0,1530.0,628.0,768.0
...,...,...,...,...,...,...,...,...,...,...,...
171661,2013,8,YV,Mesa Airlines Inc.,TRI,7.0,1.0,0.0,23.0,18.0,0.0
171662,2013,8,YV,Mesa Airlines Inc.,YUM,2.0,1.0,0.0,17.0,0.0,17.0
171663,2013,8,YV,Mesa Airlines Inc.,SLC,2.0,0.0,0.0,0.0,0.0,0.0
171664,2013,8,DL,Delta Air Lines Inc.,SBN,1.0,1.0,0.0,18.0,18.0,0.0
171665,2013,8,F9,Frontier Airlines Inc.,MTJ,1.0,0.0,0.0,0.0,0.0,0.0

In [7]:
df.drop_duplicates()

,year,month,carrier,carrier_name,airport,arr_flights,arr_del15,arr_cancelled,arr_delay,carrier_delay,late_aircraft_delay
0,2023,8,9E,Endeavor Air Inc.,ABE,89.0,13.0,2.0,1375.0,71.0,425.0
1,2023,8,9E,Endeavor Air Inc.,ABY,62.0,10.0,0.0,799.0,218.0,518.0
2,2023,8,9E,Endeavor Air Inc.,AEX,62.0,10.0,1.0,766.0,56.0,444.0
3,2023,8,9E,Endeavor Air Inc.,AGS,66.0,12.0,1.0,1397.0,471.0,218.0
4,2023,8,9E,Endeavor Air Inc.,ALB,92.0,22.0,2.0,1530.0,628.0,768.0
...,...,...,...,...,...,...,...,...,...,...,...
171661,2013,8,YV,Mesa Airlines Inc.,TRI,7.0,1.0,0.0,23.0,18.0,0.0
171662,2013,8,YV,Mesa Airlines Inc.,YUM,2.0,1.0,0.0,17.0,0.0,17.0
171663,2013,8,YV,Mesa Airlines Inc.,SLC,2.0,0.0,0.0,0.0,0.0,0.0
171664,2013,8,DL,Delta Air Lines Inc.,SBN,1.0,1.0,0.0,18.0,18.0,0.0
171665,2013,8,F9,Frontier Airlines Inc.,MTJ,1.0,0.0,0.0,0.0,0.0,0.0

In [11]:
df = df[df['year'] != 2013]
print(df)

        year  month carrier              carrier_name airport  arr_flights  \
0       2023      8      9E         Endeavor Air Inc.     ABE         89.0
1       2023      8      9E         Endeavor Air Inc.     ABY         62.0
2       2023      8      9E         Endeavor Air Inc.     AEX         62.0
3       2023      8      9E         Endeavor Air Inc.     AGS         66.0
4       2023      8      9E         Endeavor Air Inc.     ALB         92.0
...      ...    ...     ...                       ...     ...          ...
164928  2014      1      WN    Southwest Airlines Co.     SJU        282.0
164929  2014      1      WN    Southwest Airlines Co.     SLC        889.0
164930  2014      1      WN    Southwest Airlines Co.     SMF       1813.0
164931  2014      1      WN    Southwest Airlines Co.     SNA       1367.0
164932  2014      1      EV  ExpressJet Airlines Inc.     MLB          2.0

        arr_del15  arr_cancelled  arr_delay  carrier_delay  \
0            13.0            2.0     1375.0           71.0
1            10.0            0.0      799.0          218.0
2            10.0            1.0      766.0           56.0
3            12.0            1.0     1397.0          471.0
4            22.0            2.0     1530.0          628.0
...           ...            ...        ...            ...
164928      125.0            5.0     6793.0         2627.0
164929      299.0           17.0    17724.0         6330.0
164930      540.0           37.0    29340.0         7974.0
164931      340.0           24.0    16193.0         4445.0
164932        1.0            0.0       39.0           39.0

        late_aircraft_delay
0                     425.0
1                     518.0
2                     444.0
3                     218.0
4                     768.0
...                     ...
164928               2885.0
164929              10045.0
164930              20305.0
164931              11000.0
164932                  0.0

[164933 rows x 11 columns]

In [15]:
df = df[df['year'] != 2014]
print(df)

        year  month carrier            carrier_name airport  arr_flights  \
0       2023      8      9E       Endeavor Air Inc.     ABE         89.0
1       2023      8      9E       Endeavor Air Inc.     ABY         62.0
2       2023      8      9E       Endeavor Air Inc.     AEX         62.0
3       2023      8      9E       Endeavor Air Inc.     AGS         66.0
4       2023      8      9E       Endeavor Air Inc.     ALB         92.0
...      ...    ...     ...                     ...     ...          ...
150948  2015      1      WN  Southwest Airlines Co.     ONT        892.0
150949  2015      1      WN  Southwest Airlines Co.     ORF        151.0
150950  2015      1      WN  Southwest Airlines Co.     PBI        251.0
150951  2015      1      WN  Southwest Airlines Co.     PDX        793.0
150952  2015      1      WN  Southwest Airlines Co.     PHL        773.0

        arr_del15  arr_cancelled  arr_delay  carrier_delay  \
0            13.0            2.0     1375.0           71.0
1            10.0            0.0      799.0          218.0
2            10.0            1.0      766.0           56.0
3            12.0            1.0     1397.0          471.0
4            22.0            2.0     1530.0          628.0
...           ...            ...        ...            ...
150948      184.0            3.0     8431.0         2661.0
150949       45.0            0.0     2391.0          840.0
150950       68.0            6.0     3405.0         1003.0
150951      173.0            0.0     7479.0         2370.0
150952      172.0           50.0     9475.0         2818.0

        late_aircraft_delay
0                     425.0
1                     518.0
2                     444.0
3                     218.0
4                     768.0
...                     ...
150948               4526.0
150949                955.0
150950               1859.0
150951               4277.0
150952               3415.0

[150953 rows x 11 columns]

In [17]:
df = df[df['year'] != 2015]
print(df)

        year  month carrier            carrier_name airport  arr_flights  \
0       2023      8      9E       Endeavor Air Inc.     ABE         89.0
1       2023      8      9E       Endeavor Air Inc.     ABY         62.0
2       2023      8      9E       Endeavor Air Inc.     AEX         62.0
3       2023      8      9E       Endeavor Air Inc.     AGS         66.0
4       2023      8      9E       Endeavor Air Inc.     ALB         92.0
...      ...    ...     ...                     ...     ...          ...
137420  2016      1      WN  Southwest Airlines Co.     BOI        291.0
137421  2016      1      WN  Southwest Airlines Co.     BOS        904.0
137422  2016      1      WN  Southwest Airlines Co.     BUF        511.0
137423  2016      1      OO   SkyWest Airlines Inc.     LAR         52.0
137424  2016      1      DL    Delta Air Lines Inc.     DLH          1.0

        arr_del15  arr_cancelled  arr_delay  carrier_delay  \
0            13.0            2.0     1375.0           71.0
1            10.0            0.0      799.0          218.0
2            10.0            1.0      766.0           56.0
3            12.0            1.0     1397.0          471.0
4            22.0            2.0     1530.0          628.0
...           ...            ...        ...            ...
137420       30.0            1.0     1286.0          790.0
137421      137.0           27.0     6264.0         1894.0
137422       76.0           20.0     4401.0         2017.0
137423        5.0            0.0      135.0           45.0
137424        0.0            0.0        0.0            0.0

        late_aircraft_delay
0                     425.0
1                     518.0
2                     444.0
3                     218.0
4                     768.0
...                     ...
137420                474.0
137421               2738.0
137422               1793.0
137423                 54.0
137424                  0.0

[137425 rows x 11 columns]

In [19]:
df = df[df['year'] != 2016]
print(df)

        year  month carrier            carrier_name airport  arr_flights  \
0       2023      8      9E       Endeavor Air Inc.     ABE         89.0
1       2023      8      9E       Endeavor Air Inc.     ABY         62.0
2       2023      8      9E       Endeavor Air Inc.     AEX         62.0
3       2023      8      9E       Endeavor Air Inc.     AGS         66.0
4       2023      8      9E       Endeavor Air Inc.     ALB         92.0
...      ...    ...     ...                     ...     ...          ...
125203  2017      1      WN  Southwest Airlines Co.     SNA       1576.0
125204  2017      1      WN  Southwest Airlines Co.     STL       2914.0
125205  2017      1      WN  Southwest Airlines Co.     TPA       2390.0
125206  2017      1      WN  Southwest Airlines Co.     TUL        404.0
125207  2017      1      WN  Southwest Airlines Co.     TUS        372.0

        arr_del15  arr_cancelled  arr_delay  carrier_delay  \
0            13.0            2.0     1375.0           71.0
1            10.0            0.0      799.0          218.0
2            10.0            1.0      766.0           56.0
3            12.0            1.0     1397.0          471.0
4            22.0            2.0     1530.0          628.0
...           ...            ...        ...            ...
125203      484.0           34.0    21762.0         4745.0
125204      522.0           75.0    25536.0         7203.0
125205      447.0           29.0    24203.0         6666.0
125206       74.0            6.0     2905.0          993.0
125207      139.0            3.0     7033.0         1163.0

        late_aircraft_delay
0                     425.0
1                     518.0
2                     444.0
3                     218.0
4                     768.0
...                     ...
125203              13447.0
125204              13701.0
125205              12318.0
125206               1725.0
125207               5307.0

[125208 rows x 11 columns]

In [21]:
df = df[df['year'] != 2017]
print(df)

        year  month carrier       carrier_name airport  arr_flights  \
0       2023      8      9E  Endeavor Air Inc.     ABE         89.0
1       2023      8      9E  Endeavor Air Inc.     ABY         62.0
2       2023      8      9E  Endeavor Air Inc.     AEX         62.0
3       2023      8      9E  Endeavor Air Inc.     AGS         66.0
4       2023      8      9E  Endeavor Air Inc.     ALB         92.0
...      ...    ...     ...                ...     ...          ...
112685  2018      1      YX   Republic Airline     STL        258.0
112686  2018      1      YX   Republic Airline     SYR        114.0
112687  2018      1      YX   Republic Airline     TUL         67.0
112688  2018      1      YX   Republic Airline     TVC         25.0
112689  2018      1      YX   Republic Airline     XNA        140.0

        arr_del15  arr_cancelled  arr_delay  carrier_delay  \
0            13.0            2.0     1375.0           71.0
1            10.0            0.0      799.0          218.0
2            10.0            1.0      766.0           56.0
3            12.0            1.0     1397.0          471.0
4            22.0            2.0     1530.0          628.0
...           ...            ...        ...            ...
112685       38.0            7.0     1970.0          480.0
112686       27.0            5.0     1621.0          594.0
112687        5.0            2.0      235.0            7.0
112688        3.0            0.0      137.0           20.0
112689       21.0            7.0     1452.0          400.0

        late_aircraft_delay
0                     425.0
1                     518.0
2                     444.0
3                     218.0
4                     768.0
...                     ...
112685               1032.0
112686                807.0
112687                141.0
112688                 23.0
112689                600.0

[112690 rows x 11 columns]

In [23]:
df = df[df['year'] != 2018]
print(df)

       year  month carrier       carrier_name airport  arr_flights  arr_del15  \
0      2023      8      9E  Endeavor Air Inc.     ABE         89.0       13.0
1      2023      8      9E  Endeavor Air Inc.     ABY         62.0       10.0
2      2023      8      9E  Endeavor Air Inc.     AEX         62.0       10.0
3      2023      8      9E  Endeavor Air Inc.     AGS         66.0       12.0
4      2023      8      9E  Endeavor Air Inc.     ALB         92.0       22.0
...     ...    ...     ...                ...     ...          ...        ...
92472  2019      1      MQ          Envoy Air     RIC        195.0       68.0
92473  2019      1      MQ          Envoy Air     ROA         52.0       14.0
92474  2019      1      MQ          Envoy Air     ROC        106.0       26.0
92475  2019      1      MQ          Envoy Air     RST        116.0       35.0
92476  2019      1      MQ          Envoy Air     SAT         26.0        4.0

       arr_cancelled  arr_delay  carrier_delay  late_aircraft_delay
0                2.0     1375.0           71.0                425.0
1                0.0      799.0          218.0                518.0
2                1.0      766.0           56.0                444.0
3                1.0     1397.0          471.0                218.0
4                2.0     1530.0          628.0                768.0
...              ...        ...            ...                  ...
92472           22.0     4138.0          603.0               2559.0
92473            2.0      726.0          323.0                260.0
92474           17.0     1259.0          313.0                363.0
92475           22.0     2307.0          474.0                677.0
92476            5.0      120.0           50.0                 15.0

[92477 rows x 11 columns]

In [25]:
df = df[df['year'] != 2019]
print(df)

       year  month carrier       carrier_name airport  arr_flights  arr_del15  \
0      2023      8      9E  Endeavor Air Inc.     ABE         89.0       13.0
1      2023      8      9E  Endeavor Air Inc.     ABY         62.0       10.0
2      2023      8      9E  Endeavor Air Inc.     AEX         62.0       10.0
3      2023      8      9E  Endeavor Air Inc.     AGS         66.0       12.0
4      2023      8      9E  Endeavor Air Inc.     ALB         92.0       22.0
...     ...    ...     ...                ...     ...          ...        ...
71526  2020      1      YX   Republic Airline     TUS          7.0        0.0
71527  2020      1      YX   Republic Airline     TVC          1.0        0.0
71528  2020      1      YX   Republic Airline     TYS        112.0       10.0
71529  2020      1      YX   Republic Airline     VPS          8.0        1.0
71530  2020      1      YX   Republic Airline     XNA        246.0       28.0

       arr_cancelled  arr_delay  carrier_delay  late_aircraft_delay
0                2.0     1375.0           71.0                425.0
1                0.0      799.0          218.0                518.0
2                1.0      766.0           56.0                444.0
3                1.0     1397.0          471.0                218.0
4                2.0     1530.0          628.0                768.0
...              ...        ...            ...                  ...
71526            1.0        0.0            0.0                  0.0
71527            0.0        0.0            0.0                  0.0
71528            0.0      352.0           39.0                165.0
71529            0.0       47.0            0.0                  0.0
71530            0.0     1446.0          347.0                822.0

[71531 rows x 11 columns]

In [27]:
df

,year,month,carrier,carrier_name,airport,arr_flights,arr_del15,arr_cancelled,arr_delay,carrier_delay,late_aircraft_delay
0,2023,8,9E,Endeavor Air Inc.,ABE,89.0,13.0,2.0,1375.0,71.0,425.0
1,2023,8,9E,Endeavor Air Inc.,ABY,62.0,10.0,0.0,799.0,218.0,518.0
2,2023,8,9E,Endeavor Air Inc.,AEX,62.0,10.0,1.0,766.0,56.0,444.0
3,2023,8,9E,Endeavor Air Inc.,AGS,66.0,12.0,1.0,1397.0,471.0,218.0
4,2023,8,9E,Endeavor Air Inc.,ALB,92.0,22.0,2.0,1530.0,628.0,768.0
...,...,...,...,...,...,...,...,...,...,...,...
71526,2020,1,YX,Republic Airline,TUS,7.0,0.0,1.0,0.0,0.0,0.0
71527,2020,1,YX,Republic Airline,TVC,1.0,0.0,0.0,0.0,0.0,0.0
71528,2020,1,YX,Republic Airline,TYS,112.0,10.0,0.0,352.0,39.0,165.0
71529,2020,1,YX,Republic Airline,VPS,8.0,1.0,0.0,47.0,0.0,0.0
71530,2020,1,YX,Republic Airline,XNA,246.0,28.0,0.0,1446.0,347.0,822.0